
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdutxctvvwukqpxyrtku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkdXR4Y3R2dnd1a3FweHlydGt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNjE4MDEsImV4cCI6MjA2MDkzNzgwMX0.b5PIkH9GzeKQn0xwHFQh--Lw1HIYPLFVb2F7CUrtvss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
